CREATE DATABASE ASM2
USE ASM2
CREATE TABLE USERS(
UserID nvarchar(5) NOT NULL,
CONSTRAINT pk_USERS_UserID PRIMARY KEY(UserID),
UserName nvarchar(30) NOT NULL,
Password nvarchar(10),
CHECK (len(Password) between 7 and 10),
)
CREATE TABLE TOPIC(
ID nvarchar(5) NOT NULL,
CONSTRAINT pk_TOPIC_ID PRIMARY KEY(ID),
Name nvarchar(30) NOT NULL,
ParentID nvarchar(5),
CONSTRAINT fk_TOPIC_ParentID FOREIGN KEY(ParentID)
REFERENCES TOPIC(ID),
Active int DEFAULT(1),
)
CREATE TABLE MANAGER(
ManagerID nvarchar(5) NOT NULL,
CONSTRAINT pk_MANAGER_ManagerID PRIMARY KEY(ManagerID),
ManagerName nvarchar(30) NOT NULL,
AmountAuthor int,
)
ALTER TABLE MANAGER
ADD
PostDate date
Check (PostDate < getdate())

CREATE TABLE AUTHOR(
AuthorID nvarchar(5) NOT NULL,
CONSTRAINT pk_AUTHOR_AuthorID PRIMARY KEY(AuthorID),
AuthorName nvarchar(30) NOT NULL,
Place nvarchar(30),
ManagerID nvarchar(5),
CONSTRAINT fk_AUTHOR_ManagerID
FOREIGN KEY(ManagerID)
REFERENCES MANAGER(ManagerID)
ON DELETE CASCADE
ON UPDATE CASCADE,
)
CREATE TABLE ARTICLE(
ArticleID nvarchar(5) NOT NULL,
CONSTRAINT pk_ARTICLE_ArticleID PRIMARY KEY(ArticleID),
ArticleName nvarchar(150) NOT NULL,
Topic nvarchar(30),
Author nvarchar(30),
AuthorID nvarchar(5),
CONSTRAINT fk_ARTICLE_AuthorID
FOREIGN KEY(AuthorID)
REFERENCES AUTHOR(AuthorID),
ManagerID nvarchar(5)
CONSTRAINT fk_ARTICLE_ManagerID
FOREIGN KEY(ManagerID)
REFERENCES MANAGER(ManagerID),
ID nvarchar(5),
CONSTRAINT fk_ARTICLE_ID
FOREIGN KEY(ID)
REFERENCES TOPIC(ID)
ON DELETE CASCADE
ON UPDATE CASCADE,
)
ALTER TABLE ARTICLE
ADD Approve int DEFAULT(0)
CREATE TABLE AR_US(
ArticleID nvarchar(5) NOT NULL,
UserID nvarchar(5) NOT NULL,
CONSTRAINT pk_AR_US PRIMARY KEY(ArticleID, UserID),
CONSTRAINT fk_AR_US_ArticleID
FOREIGN KEY(ArticleID)
REFERENCES ARTICLE(ArticleID)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT fk_AR_US_UserID
FOREIGN KEY(UserID)
REFERENCES USERS(UserID)
ON DELETE CASCADE
ON UPDATE CASCADE,
Comment nvarchar(50),
)
